intro:
    @echo "========================================"
    @echo "1. Create custom NixOS image for a Droplet: just build-image"
    @echo "2. Upload custom image to DigitalOcean: just upload-image"
    @echo "3. Create Droplet with terraform: just create-droplet"
    @echo "4. Deploy NixOS configuration to Droplet: just deploy"
    @echo "========================================"

build-image:
    nix build

upload-image:
    @echo "Unimplemented. Do this something like:"
    @echo "curl -F'file=@result/nixos-image-digital-ocean-25.05pre-git-x86_64-linux.qcow2.gz' https://0x0.st"
    @echo "doctl compute image create nixos --image-url https://0x0.st/8EfQ.qcow2.gz --region sgp1"

create-droplet:
    @echo "Ensure DIGITALOCEAN_TOKEN is set in your environment."
    @echo "Obtain from ~/doctl/config.yaml if needed."
    terraform apply -auto-approve

deploy:
    nixos-rebuild switch \
        --target-host root@cloud.heyzec.dedyn.io \
        --flake .#nixie-droplet
